/* The following code was generated by JFlex 1.4.3 on 2/02/21 11:40 PM */

package anaa;
import static anaa.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 2/02/21 11:40 PM from the specification file
 * <tt>C:/Users/sebas/udistri/octavo/Ciencias3/AnalizadorFinal/anaa/anaa/src/anaa/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\5\2\0\1\3\22\0\1\3\1\42\1\6\2\0"+
    "\1\37\1\40\1\61\1\44\1\45\1\36\1\34\1\57\1\35\1\60"+
    "\1\4\12\2\1\60\1\60\1\43\1\33\1\43\2\0\22\1\1\30"+
    "\7\1\1\50\1\0\1\51\1\0\1\1\1\0\1\17\1\7\1\15"+
    "\1\25\1\12\1\24\1\23\1\16\1\13\1\1\1\32\1\21\1\52"+
    "\1\14\1\22\1\53\1\1\1\20\1\27\1\11\1\26\1\55\1\31"+
    "\1\54\1\10\1\56\1\46\1\41\1\47\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\16\2\1\10\1\11\1\12\1\13\1\14\3\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\3\2\1\25"+
    "\1\26\1\27\1\4\1\30\11\2\1\31\20\2\1\32"+
    "\7\2\1\16\1\33\1\15\1\0\12\2\1\34\5\2"+
    "\1\35\2\2\1\36\15\2\1\37\12\2\1\0\7\2"+
    "\1\35\2\2\1\40\2\2\1\41\1\42\1\43\7\2"+
    "\1\44\21\2\1\3\1\45\4\2\1\46\1\2\1\47"+
    "\1\2\1\50\7\2\1\51\1\52\1\2\1\53\3\2"+
    "\1\54\4\2\1\55\2\2\1\56\6\2\1\57\5\2"+
    "\1\60\1\61\2\2\1\62\1\63\3\2\1\64\1\2"+
    "\1\65\1\66\3\2\1\67\2\2\1\70\5\2\1\71"+
    "\1\72\2\2\1\73\1\74\6\2\1\75\1\76\1\2"+
    "\1\77\1\2\1\100\1\101\1\102\3\2\1\103\1\104"+
    "\1\105\2\2\1\106";

  private static int [] zzUnpackAction() {
    int [] result = new int[269];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\62\0\62"+
    "\0\u012c\0\u015e\0\u0190\0\u01c2\0\u01f4\0\u0226\0\u0258\0\u028a"+
    "\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6\0\u03e8\0\u041a"+
    "\0\u044c\0\u047e\0\u047e\0\u04b0\0\u04e2\0\u03e8\0\u03e8\0\u0514"+
    "\0\62\0\62\0\62\0\62\0\62\0\u0546\0\u0578\0\u05aa"+
    "\0\62\0\62\0\62\0\u05dc\0\62\0\u060e\0\u0640\0\u0672"+
    "\0\u06a4\0\u06d6\0\u0708\0\u073a\0\u076c\0\u079e\0\144\0\u07d0"+
    "\0\u0802\0\u0834\0\u0866\0\u0898\0\u08ca\0\u08fc\0\u092e\0\u0960"+
    "\0\u0992\0\u09c4\0\u09f6\0\u0a28\0\u0a5a\0\u0a8c\0\u0abe\0\u0af0"+
    "\0\u0b22\0\u0b54\0\u0b86\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e\0\62"+
    "\0\62\0\62\0\u0c80\0\u0cb2\0\u0ce4\0\u0d16\0\u0d48\0\u0d7a"+
    "\0\u0dac\0\u0dde\0\u0e10\0\u0e42\0\u0e74\0\144\0\u0ea6\0\u0ed8"+
    "\0\u0f0a\0\u0f3c\0\u0f6e\0\u0fa0\0\u0fd2\0\u1004\0\144\0\u1036"+
    "\0\u1068\0\u109a\0\u10cc\0\u10fe\0\u1130\0\u1162\0\u1194\0\u11c6"+
    "\0\u11f8\0\u122a\0\u125c\0\u128e\0\144\0\u12c0\0\u12f2\0\u1324"+
    "\0\u1356\0\u1388\0\u13ba\0\u13ec\0\u141e\0\u1450\0\u1482\0\u14b4"+
    "\0\u14e6\0\u1518\0\u154a\0\u157c\0\u15ae\0\u15e0\0\u1612\0\144"+
    "\0\u1644\0\u1676\0\144\0\u16a8\0\u16da\0\144\0\144\0\144"+
    "\0\u170c\0\u173e\0\u1770\0\u17a2\0\u17d4\0\u1806\0\u1838\0\144"+
    "\0\u186a\0\u189c\0\u18ce\0\u1900\0\u1932\0\u1964\0\u1996\0\u19c8"+
    "\0\u19fa\0\u1a2c\0\u1a5e\0\u1a90\0\u1ac2\0\u1af4\0\u1b26\0\u1b58"+
    "\0\u1b8a\0\62\0\144\0\u1bbc\0\u1bee\0\u1c20\0\u1c52\0\144"+
    "\0\u1c84\0\144\0\u1cb6\0\u1ce8\0\u1d1a\0\u1d4c\0\u1d7e\0\u1db0"+
    "\0\u1de2\0\u1e14\0\u1e46\0\144\0\144\0\u1e78\0\144\0\u1eaa"+
    "\0\u1edc\0\u1f0e\0\u1f40\0\u1f72\0\u1fa4\0\u1fd6\0\u2008\0\144"+
    "\0\u203a\0\u206c\0\144\0\u209e\0\u20d0\0\u2102\0\u2134\0\u2166"+
    "\0\u2198\0\144\0\u21ca\0\u21fc\0\u222e\0\u2260\0\u2292\0\144"+
    "\0\144\0\u22c4\0\u22f6\0\144\0\144\0\u2328\0\u235a\0\u238c"+
    "\0\144\0\u23be\0\144\0\144\0\u23f0\0\u2422\0\u2454\0\144"+
    "\0\u2486\0\u24b8\0\144\0\u24ea\0\u251c\0\u254e\0\u2580\0\u25b2"+
    "\0\144\0\144\0\u25e4\0\u2616\0\144\0\144\0\u2648\0\u267a"+
    "\0\u26ac\0\u26de\0\u2710\0\u2742\0\144\0\144\0\u2774\0\144"+
    "\0\u27a6\0\144\0\144\0\144\0\u27d8\0\u280a\0\u283c\0\144"+
    "\0\144\0\144\0\u286e\0\u28a0\0\144";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[269];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\3\1\12\1\13\1\14\1\15\1\16\1\3\1\17"+
    "\1\20\1\21\2\3\1\22\1\23\1\3\1\24\1\25"+
    "\1\26\1\3\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\3\1\50\1\3\1\51\1\52"+
    "\1\53\63\0\2\3\4\0\24\3\17\0\5\3\5\0"+
    "\1\4\62\0\1\5\62\0\1\54\26\0\1\55\27\0"+
    "\2\3\4\0\1\3\1\56\7\3\1\57\1\3\1\60"+
    "\10\3\17\0\5\3\4\0\2\3\4\0\7\3\1\61"+
    "\1\3\1\62\12\3\17\0\5\3\4\0\2\3\4\0"+
    "\5\3\1\63\4\3\1\64\11\3\17\0\2\3\1\65"+
    "\2\3\4\0\2\3\4\0\5\3\1\66\7\3\1\67"+
    "\6\3\17\0\1\70\4\3\4\0\2\3\4\0\3\3"+
    "\1\71\4\3\1\72\13\3\17\0\5\3\4\0\2\3"+
    "\4\0\7\3\1\73\1\74\1\3\1\75\1\76\10\3"+
    "\17\0\5\3\4\0\2\3\4\0\1\77\17\3\1\100"+
    "\3\3\17\0\5\3\4\0\2\3\4\0\3\3\1\101"+
    "\20\3\17\0\5\3\4\0\2\3\4\0\13\3\1\102"+
    "\10\3\17\0\5\3\4\0\2\3\4\0\4\3\1\103"+
    "\3\3\1\104\1\3\1\105\1\106\10\3\17\0\5\3"+
    "\4\0\2\3\4\0\3\3\1\107\7\3\1\110\10\3"+
    "\17\0\5\3\4\0\2\3\4\0\1\3\1\111\1\112"+
    "\4\3\1\113\7\3\1\114\2\3\1\115\1\3\17\0"+
    "\5\3\4\0\2\3\4\0\2\3\1\116\21\3\17\0"+
    "\5\3\4\0\2\3\4\0\7\3\1\117\14\3\17\0"+
    "\5\3\36\0\1\120\61\0\1\55\1\121\60\0\1\55"+
    "\1\0\1\121\57\0\1\55\66\0\1\122\62\0\1\122"+
    "\55\0\1\123\25\0\2\3\4\0\10\3\1\124\13\3"+
    "\17\0\5\3\4\0\2\3\4\0\10\3\1\125\1\126"+
    "\5\3\1\127\4\3\17\0\5\3\4\0\2\3\4\0"+
    "\13\3\1\130\10\3\17\0\5\3\3\0\5\54\1\0"+
    "\54\54\1\0\2\3\4\0\2\3\1\131\21\3\17\0"+
    "\5\3\4\0\2\3\4\0\3\3\1\132\20\3\17\0"+
    "\5\3\4\0\2\3\4\0\13\3\1\133\10\3\17\0"+
    "\5\3\4\0\2\3\4\0\4\3\1\134\4\3\1\135"+
    "\12\3\17\0\5\3\4\0\2\3\4\0\1\3\1\136"+
    "\6\3\1\137\6\3\1\140\4\3\17\0\5\3\4\0"+
    "\2\3\4\0\17\3\1\141\4\3\17\0\5\3\4\0"+
    "\2\3\4\0\20\3\1\142\3\3\17\0\5\3\4\0"+
    "\2\3\4\0\2\3\1\143\21\3\17\0\5\3\4\0"+
    "\2\3\4\0\2\3\1\144\15\3\1\145\3\3\17\0"+
    "\5\3\4\0\2\3\4\0\24\3\17\0\1\3\1\146"+
    "\3\3\4\0\2\3\4\0\22\3\1\147\1\3\17\0"+
    "\5\3\4\0\2\3\4\0\2\3\1\150\21\3\17\0"+
    "\5\3\4\0\2\3\4\0\10\3\1\151\13\3\17\0"+
    "\5\3\4\0\2\3\4\0\2\3\1\152\15\3\1\153"+
    "\3\3\17\0\5\3\4\0\2\3\4\0\10\3\1\154"+
    "\13\3\17\0\5\3\4\0\2\3\4\0\5\3\1\155"+
    "\16\3\17\0\5\3\4\0\2\3\4\0\20\3\1\156"+
    "\3\3\17\0\5\3\4\0\2\3\4\0\20\3\1\157"+
    "\3\3\17\0\5\3\4\0\2\3\4\0\2\3\1\160"+
    "\21\3\17\0\5\3\4\0\2\3\4\0\5\3\1\161"+
    "\16\3\17\0\5\3\4\0\2\3\4\0\5\3\1\162"+
    "\16\3\17\0\5\3\4\0\2\3\4\0\12\3\1\163"+
    "\11\3\17\0\5\3\4\0\2\3\4\0\13\3\1\164"+
    "\10\3\17\0\5\3\4\0\2\3\4\0\11\3\1\165"+
    "\12\3\17\0\5\3\4\0\2\3\4\0\15\3\1\166"+
    "\6\3\17\0\5\3\4\0\2\3\4\0\17\3\1\167"+
    "\4\3\17\0\5\3\4\0\2\3\4\0\5\3\1\170"+
    "\16\3\17\0\5\3\4\0\2\3\4\0\10\3\1\171"+
    "\1\172\12\3\17\0\5\3\4\0\2\3\4\0\13\3"+
    "\1\173\10\3\17\0\5\3\4\0\2\3\4\0\24\3"+
    "\17\0\1\3\1\174\3\3\4\0\2\3\4\0\4\3"+
    "\1\175\17\3\17\0\5\3\4\0\2\3\4\0\11\3"+
    "\1\176\12\3\17\0\5\3\4\0\2\3\4\0\4\3"+
    "\1\177\17\3\17\0\5\3\5\0\1\200\60\0\2\3"+
    "\4\0\4\3\1\201\17\3\17\0\5\3\4\0\2\3"+
    "\4\0\6\3\1\202\15\3\17\0\5\3\4\0\2\3"+
    "\4\0\4\3\1\203\6\3\1\204\10\3\17\0\5\3"+
    "\4\0\2\3\4\0\1\205\23\3\17\0\5\3\4\0"+
    "\2\3\4\0\4\3\1\206\5\3\1\207\11\3\17\0"+
    "\5\3\4\0\2\3\4\0\3\3\1\210\20\3\17\0"+
    "\5\3\4\0\2\3\4\0\10\3\1\211\13\3\17\0"+
    "\5\3\4\0\2\3\4\0\12\3\1\212\11\3\17\0"+
    "\5\3\4\0\2\3\4\0\20\3\1\213\3\3\17\0"+
    "\5\3\4\0\2\3\4\0\13\3\1\214\10\3\17\0"+
    "\5\3\4\0\2\3\4\0\5\3\1\215\16\3\17\0"+
    "\5\3\4\0\2\3\4\0\3\3\1\216\20\3\17\0"+
    "\5\3\4\0\2\3\4\0\24\3\17\0\1\217\4\3"+
    "\4\0\2\3\4\0\3\3\1\220\20\3\17\0\5\3"+
    "\4\0\2\3\4\0\3\3\1\221\20\3\17\0\5\3"+
    "\4\0\2\3\4\0\3\3\1\222\20\3\17\0\5\3"+
    "\4\0\2\3\4\0\2\3\1\223\21\3\17\0\5\3"+
    "\4\0\2\3\4\0\12\3\1\224\1\225\10\3\17\0"+
    "\5\3\4\0\2\3\4\0\4\3\1\226\17\3\17\0"+
    "\5\3\4\0\2\3\4\0\11\3\1\210\12\3\17\0"+
    "\5\3\4\0\2\3\4\0\6\3\1\227\15\3\17\0"+
    "\5\3\4\0\2\3\4\0\3\3\1\230\20\3\17\0"+
    "\5\3\4\0\2\3\4\0\20\3\1\231\3\3\17\0"+
    "\5\3\4\0\2\3\4\0\2\3\1\232\15\3\1\233"+
    "\3\3\17\0\5\3\4\0\2\3\4\0\2\3\1\234"+
    "\21\3\17\0\5\3\4\0\2\3\4\0\3\3\1\235"+
    "\20\3\17\0\5\3\4\0\2\3\4\0\17\3\1\236"+
    "\4\3\17\0\5\3\4\0\2\3\4\0\14\3\1\210"+
    "\7\3\17\0\5\3\4\0\2\3\4\0\10\3\1\237"+
    "\13\3\17\0\5\3\4\0\2\3\4\0\20\3\1\140"+
    "\3\3\17\0\5\3\4\0\2\3\4\0\10\3\1\240"+
    "\13\3\17\0\5\3\4\0\2\3\4\0\10\3\1\241"+
    "\13\3\17\0\5\3\4\0\2\3\4\0\1\242\23\3"+
    "\17\0\5\3\4\0\2\3\4\0\6\3\1\243\15\3"+
    "\17\0\5\3\4\0\2\3\4\0\2\3\1\244\21\3"+
    "\17\0\5\3\4\0\2\3\4\0\4\3\1\245\17\3"+
    "\17\0\5\3\4\0\2\3\4\0\11\3\1\240\12\3"+
    "\17\0\5\3\4\0\2\3\4\0\3\3\1\246\20\3"+
    "\17\0\5\3\4\0\2\3\4\0\2\3\1\247\21\3"+
    "\17\0\5\3\4\0\2\3\4\0\4\3\1\250\17\3"+
    "\17\0\5\3\4\0\2\3\4\0\12\3\1\251\11\3"+
    "\17\0\5\3\5\0\1\200\42\0\1\252\15\0\2\3"+
    "\4\0\5\3\1\253\16\3\17\0\5\3\4\0\2\3"+
    "\4\0\23\3\1\254\17\0\5\3\4\0\2\3\4\0"+
    "\24\3\17\0\3\3\1\255\1\3\4\0\2\3\4\0"+
    "\2\3\1\256\21\3\17\0\5\3\4\0\2\3\4\0"+
    "\12\3\1\257\11\3\17\0\5\3\4\0\2\3\4\0"+
    "\16\3\1\260\5\3\17\0\5\3\4\0\2\3\4\0"+
    "\10\3\1\261\13\3\17\0\5\3\4\0\2\3\4\0"+
    "\23\3\1\262\17\0\5\3\4\0\2\3\4\0\3\3"+
    "\1\263\20\3\17\0\5\3\4\0\2\3\4\0\22\3"+
    "\1\264\1\3\17\0\5\3\4\0\2\3\4\0\20\3"+
    "\1\265\3\3\17\0\5\3\4\0\2\3\4\0\5\3"+
    "\1\266\16\3\17\0\5\3\4\0\2\3\4\0\11\3"+
    "\1\267\12\3\17\0\5\3\4\0\2\3\4\0\10\3"+
    "\1\270\13\3\17\0\5\3\4\0\2\3\4\0\3\3"+
    "\1\271\20\3\17\0\5\3\4\0\2\3\4\0\11\3"+
    "\1\272\12\3\17\0\5\3\4\0\2\3\4\0\24\3"+
    "\17\0\3\3\1\273\1\3\4\0\2\3\4\0\7\3"+
    "\1\274\14\3\17\0\5\3\4\0\2\3\4\0\20\3"+
    "\1\275\3\3\17\0\5\3\4\0\2\3\4\0\4\3"+
    "\1\276\17\3\17\0\5\3\4\0\2\3\4\0\2\3"+
    "\1\277\21\3\17\0\5\3\4\0\2\3\4\0\11\3"+
    "\1\300\12\3\17\0\5\3\4\0\2\3\4\0\11\3"+
    "\1\301\12\3\17\0\5\3\4\0\2\3\4\0\11\3"+
    "\1\302\12\3\17\0\5\3\4\0\2\3\4\0\12\3"+
    "\1\303\11\3\17\0\5\3\4\0\2\3\4\0\2\3"+
    "\1\210\21\3\17\0\5\3\4\0\2\3\4\0\17\3"+
    "\1\304\4\3\17\0\5\3\4\0\2\3\4\0\12\3"+
    "\1\131\11\3\17\0\5\3\4\0\2\3\4\0\7\3"+
    "\1\305\14\3\17\0\5\3\4\0\2\3\4\0\4\3"+
    "\1\306\17\3\17\0\5\3\4\0\2\3\4\0\6\3"+
    "\1\307\15\3\17\0\5\3\4\0\2\3\4\0\11\3"+
    "\1\310\12\3\17\0\5\3\4\0\2\3\4\0\6\3"+
    "\1\311\15\3\17\0\5\3\4\0\2\3\4\0\5\3"+
    "\1\312\16\3\17\0\5\3\4\0\2\3\4\0\3\3"+
    "\1\313\20\3\17\0\5\3\4\0\2\3\4\0\10\3"+
    "\1\314\13\3\17\0\5\3\4\0\2\3\4\0\10\3"+
    "\1\315\13\3\17\0\5\3\4\0\2\3\4\0\3\3"+
    "\1\316\20\3\17\0\5\3\4\0\2\3\4\0\4\3"+
    "\1\317\17\3\17\0\5\3\4\0\2\3\4\0\2\3"+
    "\1\320\21\3\17\0\5\3\4\0\2\3\4\0\10\3"+
    "\1\321\13\3\17\0\5\3\4\0\2\3\4\0\20\3"+
    "\1\322\3\3\17\0\5\3\4\0\2\3\4\0\4\3"+
    "\1\323\17\3\17\0\5\3\4\0\2\3\4\0\16\3"+
    "\1\324\5\3\17\0\5\3\4\0\2\3\4\0\15\3"+
    "\1\325\6\3\17\0\5\3\4\0\2\3\4\0\5\3"+
    "\1\326\16\3\17\0\5\3\4\0\2\3\4\0\24\3"+
    "\17\0\1\327\4\3\4\0\2\3\4\0\2\3\1\330"+
    "\21\3\17\0\5\3\4\0\2\3\4\0\3\3\1\331"+
    "\20\3\17\0\5\3\4\0\2\3\4\0\5\3\1\332"+
    "\16\3\17\0\5\3\4\0\2\3\4\0\10\3\1\333"+
    "\13\3\17\0\5\3\4\0\2\3\4\0\2\3\1\334"+
    "\21\3\17\0\5\3\4\0\2\3\4\0\5\3\1\335"+
    "\16\3\17\0\5\3\4\0\2\3\4\0\12\3\1\336"+
    "\11\3\17\0\5\3\4\0\2\3\4\0\12\3\1\337"+
    "\11\3\17\0\5\3\4\0\2\3\4\0\11\3\1\340"+
    "\12\3\17\0\5\3\4\0\2\3\4\0\6\3\1\341"+
    "\15\3\17\0\5\3\4\0\2\3\4\0\2\3\1\342"+
    "\21\3\17\0\5\3\4\0\2\3\4\0\7\3\1\343"+
    "\14\3\17\0\5\3\4\0\2\3\4\0\14\3\1\344"+
    "\7\3\17\0\5\3\4\0\2\3\4\0\14\3\1\345"+
    "\7\3\17\0\5\3\4\0\2\3\4\0\2\3\1\346"+
    "\21\3\17\0\5\3\4\0\2\3\4\0\6\3\1\347"+
    "\15\3\17\0\5\3\4\0\2\3\4\0\6\3\1\350"+
    "\15\3\17\0\5\3\4\0\2\3\4\0\4\3\1\351"+
    "\17\3\17\0\5\3\4\0\2\3\4\0\5\3\1\210"+
    "\16\3\17\0\5\3\4\0\2\3\4\0\3\3\1\352"+
    "\20\3\17\0\5\3\4\0\2\3\4\0\20\3\1\353"+
    "\3\3\17\0\5\3\4\0\2\3\4\0\10\3\1\354"+
    "\13\3\17\0\5\3\4\0\2\3\4\0\6\3\1\355"+
    "\15\3\17\0\5\3\4\0\2\3\4\0\3\3\1\356"+
    "\20\3\17\0\5\3\4\0\2\3\4\0\17\3\1\357"+
    "\4\3\17\0\5\3\4\0\2\3\4\0\6\3\1\360"+
    "\15\3\17\0\5\3\4\0\2\3\4\0\1\3\1\361"+
    "\22\3\17\0\5\3\4\0\2\3\4\0\2\3\1\362"+
    "\21\3\17\0\5\3\4\0\2\3\4\0\13\3\1\363"+
    "\10\3\17\0\5\3\4\0\2\3\4\0\15\3\1\364"+
    "\6\3\17\0\5\3\4\0\2\3\4\0\3\3\1\365"+
    "\20\3\17\0\5\3\4\0\2\3\4\0\3\3\1\366"+
    "\20\3\17\0\5\3\4\0\2\3\4\0\2\3\1\367"+
    "\21\3\17\0\5\3\4\0\2\3\4\0\12\3\1\370"+
    "\11\3\17\0\5\3\4\0\2\3\4\0\5\3\1\371"+
    "\16\3\17\0\5\3\4\0\2\3\4\0\6\3\1\372"+
    "\15\3\17\0\5\3\4\0\2\3\4\0\3\3\1\373"+
    "\20\3\17\0\5\3\4\0\2\3\4\0\5\3\1\374"+
    "\16\3\17\0\5\3\4\0\2\3\4\0\3\3\1\375"+
    "\20\3\17\0\5\3\4\0\2\3\4\0\2\3\1\376"+
    "\21\3\17\0\5\3\4\0\2\3\4\0\5\3\1\377"+
    "\16\3\17\0\5\3\4\0\2\3\4\0\24\3\17\0"+
    "\1\3\1\u0100\3\3\4\0\2\3\4\0\3\3\1\u0101"+
    "\20\3\17\0\5\3\4\0\2\3\4\0\3\3\1\u0102"+
    "\20\3\17\0\5\3\4\0\2\3\4\0\2\3\1\u0103"+
    "\21\3\17\0\5\3\4\0\2\3\4\0\3\3\1\u0104"+
    "\20\3\17\0\5\3\4\0\2\3\4\0\13\3\1\u0105"+
    "\10\3\17\0\5\3\4\0\2\3\4\0\2\3\1\u0106"+
    "\21\3\17\0\5\3\4\0\2\3\4\0\4\3\1\u0107"+
    "\17\3\17\0\5\3\4\0\2\3\4\0\16\3\1\u0108"+
    "\5\3\17\0\5\3\4\0\2\3\4\0\15\3\1\u0109"+
    "\6\3\17\0\5\3\4\0\2\3\4\0\20\3\1\u010a"+
    "\3\3\17\0\5\3\4\0\2\3\4\0\24\3\17\0"+
    "\4\3\1\u010b\4\0\2\3\4\0\3\3\1\u010c\20\3"+
    "\17\0\5\3\4\0\2\3\4\0\16\3\1\u010d\5\3"+
    "\17\0\5\3\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10450];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\2\11\30\1\5\11\3\1\3\11"+
    "\1\1\1\11\42\1\3\11\1\0\54\1\1\0\51\1"+
    "\1\11\143\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[269];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 134) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 22: 
          { lexeme=yytext(); return signo_puntuacion;
          }
        case 71: break;
        case 39: 
          { lexeme=yytext(); return Break;
          }
        case 72: break;
        case 2: 
          { lexeme=yytext(); return Identificador;
          }
        case 73: break;
        case 12: 
          { lexeme=yytext(); return Modulo;
          }
        case 74: break;
        case 43: 
          { lexeme=yytext(); return Const;
          }
        case 75: break;
        case 30: 
          { lexeme=yytext(); return New;
          }
        case 76: break;
        case 61: 
          { lexeme=yytext(); return Continue;
          }
        case 77: break;
        case 50: 
          { lexeme=yytext(); return Assert;
          }
        case 78: break;
        case 29: 
          { lexeme=yytext(); return Tipo_dato;
          }
        case 79: break;
        case 13: 
          { lexeme=yytext(); return Operador_logico;
          }
        case 80: break;
        case 41: 
          { lexeme=yytext(); return Catch;
          }
        case 81: break;
        case 34: 
          { lexeme=yytext(); return Enum;
          }
        case 82: break;
        case 35: 
          { lexeme=yytext(); return Else;
          }
        case 83: break;
        case 51: 
          { lexeme=yytext(); return Return;
          }
        case 84: break;
        case 60: 
          { lexeme=yytext(); return Private;
          }
        case 85: break;
        case 36: 
          { lexeme=yytext(); return Case;
          }
        case 86: break;
        case 19: 
          { lexeme = yytext(); return Corchete_apertura;
          }
        case 87: break;
        case 38: 
          { lexeme=yytext(); return Void;
          }
        case 88: break;
        case 27: 
          { lexeme = yytext(); return Operador_unario;
          }
        case 89: break;
        case 18: 
          { lexeme=yytext(); return Llave_cierre;
          }
        case 90: break;
        case 6: 
          { return Linea;
          }
        case 91: break;
        case 31: 
          { lexeme=yytext(); return For;
          }
        case 92: break;
        case 55: 
          { lexeme=yytext(); return Public;
          }
        case 93: break;
        case 20: 
          { lexeme = yytext(); return Corchete_cierre;
          }
        case 94: break;
        case 70: 
          { lexeme=yytext(); return Synchronized;
          }
        case 95: break;
        case 56: 
          { lexeme=yytext(); return Extends;
          }
        case 96: break;
        case 52: 
          { lexeme=yytext(); return Static;
          }
        case 97: break;
        case 64: 
          { lexeme=yytext(); return Volatile;
          }
        case 98: break;
        case 5: 
          { lexeme=yytext(); return Division;
          }
        case 99: break;
        case 28: 
          { lexeme=yytext(); return Try;
          }
        case 100: break;
        case 65: 
          { lexeme=yytext(); return Transient;
          }
        case 101: break;
        case 3: 
          { lexeme=yytext(); return Numero;
          }
        case 102: break;
        case 14: 
          { lexeme = yytext(); return Operador_relacional;
          }
        case 103: break;
        case 69: 
          { lexeme=yytext(); return Implements;
          }
        case 104: break;
        case 23: 
          { lexeme=yytext(); return Comilla;
          }
        case 105: break;
        case 7: 
          { lexeme=yytext(); return Comillas;
          }
        case 106: break;
        case 67: 
          { lexeme=yytext(); return Protected;
          }
        case 107: break;
        case 17: 
          { lexeme=yytext(); return Llave_apertura;
          }
        case 108: break;
        case 59: 
          { lexeme=yytext(); return Package;
          }
        case 109: break;
        case 54: 
          { lexeme=yytext(); return Cadena;
          }
        case 110: break;
        case 47: 
          { lexeme=yytext(); return Throws;
          }
        case 111: break;
        case 62: 
          { lexeme=yytext(); return Abstract;
          }
        case 112: break;
        case 57: 
          { lexeme=yytext(); return Finally;
          }
        case 113: break;
        case 26: 
          { lexeme=yytext(); return Do;
          }
        case 114: break;
        case 49: 
          { lexeme=yytext(); return Native;
          }
        case 115: break;
        case 58: 
          { lexeme=yytext(); return Default;
          }
        case 116: break;
        case 16: 
          { lexeme=yytext(); return Parentesis_cierre;
          }
        case 117: break;
        case 37: 
          { lexeme=yytext(); return Main;
          }
        case 118: break;
        case 10: 
          { lexeme=yytext(); return Resta;
          }
        case 119: break;
        case 66: 
          { lexeme=yytext(); return Interface;
          }
        case 120: break;
        case 53: 
          { lexeme=yytext(); return Switch;
          }
        case 121: break;
        case 45: 
          { lexeme=yytext(); return Super;
          }
        case 122: break;
        case 68: 
          { lexeme=yytext(); return Instanceof;
          }
        case 123: break;
        case 11: 
          { lexeme=yytext(); return Multiplicacion;
          }
        case 124: break;
        case 63: 
          { lexeme=yytext(); return Strictfp;
          }
        case 125: break;
        case 42: 
          { lexeme=yytext(); return Class;
          }
        case 126: break;
        case 40: 
          { lexeme=yytext(); return Throw;
          }
        case 127: break;
        case 1: 
          { return ERROR;
          }
        case 128: break;
        case 33: 
          { lexeme = yytext(); return Dato_booleano;
          }
        case 129: break;
        case 8: 
          { lexeme=yytext(); return Igual;
          }
        case 130: break;
        case 48: 
          { lexeme=yytext(); return Import;
          }
        case 131: break;
        case 21: 
          { lexeme=yytext(); return Coma;
          }
        case 132: break;
        case 15: 
          { lexeme=yytext(); return Parentesis_apertura;
          }
        case 133: break;
        case 46: 
          { lexeme=yytext(); return While;
          }
        case 134: break;
        case 44: 
          { lexeme=yytext(); return Final;
          }
        case 135: break;
        case 4: 
          { /*Ignore*/
          }
        case 136: break;
        case 25: 
          { lexeme=yytext(); return If;
          }
        case 137: break;
        case 24: 
          { lexeme = yytext(); return Operador_asignacion;
          }
        case 138: break;
        case 32: 
          { lexeme=yytext(); return This;
          }
        case 139: break;
        case 9: 
          { lexeme=yytext(); return Suma;
          }
        case 140: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
