
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 15 16:16:35 COT 2021
//----------------------------------------------------

package anaa;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 25;
  public static final int Coma = 42;
  public static final int Llave_c = 37;
  public static final int Op_booleano = 33;
  public static final int Llave_a = 36;
  public static final int If = 6;
  public static final int Void = 18;
  public static final int T_dato = 3;
  public static final int Default = 10;
  public static final int Asterisco = 22;
  public static final int Else = 7;
  public static final int Cout = 46;
  public static final int Break = 29;
  public static final int Corchete_c = 39;
  public static final int Corchete_a = 38;
  public static final int Long = 12;
  public static final int Punto = 48;
  public static final int Return = 26;
  public static final int While = 9;
  public static final int Division = 23;
  public static final int Int = 4;
  public static final int Parentesis_c = 35;
  public static final int Cadena = 5;
  public static final int Float = 15;
  public static final int Dos_p = 30;
  public static final int Parentesis_a = 34;
  public static final int For = 11;
  public static final int P_coma = 41;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Switch = 27;
  public static final int Char = 16;
  public static final int Op_atribucion = 31;
  public static final int Do = 8;
  public static final int Op_logico = 24;
  public static final int Case = 28;
  public static final int Identificador = 43;
  public static final int Struct = 47;
  public static final int Cin = 45;
  public static final int DOuble = 13;
  public static final int Resta = 21;
  public static final int Caracter = 17;
  public static final int Op_incremento = 32;
  public static final int Numero = 44;
  public static final int Suma = 20;
  public static final int Main = 40;
  public static final int Igual = 19;
  public static final int Comilla = 14;
  public static final int Comillas = 2;
}

