
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 02 23:40:42 COT 2021
//----------------------------------------------------

package anaa;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Dospuntos = 35;
  public static final int Llave_cierre = 21;
  public static final int Llave_apertura = 20;
  public static final int Class = 28;
  public static final int Coma = 29;
  public static final int Parentesis_apertura = 18;
  public static final int If = 5;
  public static final int Void = 31;
  public static final int Default = 22;
  public static final int Interface = 25;
  public static final int Else = 6;
  public static final int Enum = 23;
  public static final int Break = 10;
  public static final int Operador_unario = 15;
  public static final int Tipo_dato = 3;
  public static final int While = 8;
  public static final int Cadena = 4;
  public static final int Operador_incremento = 14;
  public static final int For = 9;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Switch = 11;
  public static final int Operador_relacional = 16;
  public static final int PuntoyComa = 34;
  public static final int Private = 33;
  public static final int Parentesis_cierre = 19;
  public static final int Do = 7;
  public static final int Case = 12;
  public static final int Public = 30;
  public static final int Protected = 32;
  public static final int Operador_asignacion = 24;
  public static final int New = 27;
  public static final int Identificador = 36;
  public static final int Numero = 37;
  public static final int Dato_booleano = 17;
  public static final int Igual = 13;
  public static final int Abstract = 26;
  public static final int Comillas = 2;
}

